---
title: "WGCNA visualizations"
author: "Menna Arafat"
date: "2024-3-10"
output: html_document
---

## create directtories

```{r}
dir.create("output")
dir.create("plots")
```

## load libraries

```{r}
suppressPackageStartupMessages({ 
  
library(tidyr)
library(purrr)
library(tibble)
library(tidyverse)
library(gridExtra)
library(gtools)
library(pROC)
library(ape)
library(ggdendro)
library(WGCNA)
library(stats)
library(flashClust)
library(plyr)
library(dplyr)
library(tidyr)
library(purrr)
library(tibble)
library(tidyverse)
library(gridExtra)
library(gplots)
library(ggplot2)
library(circlize)
library(ComplexHeatmap)
allowWGCNAThreads()          # allow multi-threading (optional)

})

```
## load data

```{r}
data= read.csv("data/cancer_proteome.csv" )[-1,] 

## remove duplicte proteins
data= data[!duplicated(data$Gene),]
sum(duplicated(data$X))
```


```{r}
## set row names
row.names(data)= NULL
data = data %>% column_to_rownames(var = "Gene")
data[]= lapply(data, as.numeric)
colnames(data)= c(paste0("cancer_subtype.x.", 1:4), paste0("cancer_subtype.y.", 1:4), paste0("Ctrl.", 1:4))
head(data)

goods <- goodSamplesGenes(datExpr, verbose = 3)
datExpr= datExpr[goods$goodSamples== TRUE, goods$goodGenes == TRUE ] #so that samples become in row
data=t(datExpr) %>% as.data.frame()


```

## metadata

```{r}
metadata= data.frame(Sample= colnames(data) ,
                     condition= ifelse(grepl("subtype.x", colnames(data)),"subtype.x",
                                       ifelse(grepl("subtype.y", colnames(data)),"subtype.y", "Ctrl"))) %>% 
                                        column_to_rownames(var = "Sample")


design= model.matrix(~ 0+condition , metadata) %>% as.data.frame()
colnames(design) = gsub("condition", "", colnames(design))
design


metadata$cond_binary= ifelse(grepl("subtype.x", metadata$condition), 1,
                             ifelse(grepl("subtype.y", metadata$condition),2, 3))


```

```{r}

#parameters for WGCNA
power= 11  #we raise the adjacency matrix to this power to get rid of weak edges, hence emphasizing only strong correlations and ensure that the network degree follow a scale free distribution, recommended to be less than 15 for unsigned or signed hybrid networks, and less than 30 for signed networks  
minModuleSize = 25 # minimum module size is the minimum number of genes per module usually (minModuleSize = 50)
networkType = "signed" #as for unsigned network, negative correlations are treated the same as positive correlations. While for signed network, it gives more weight to positive correlations and consider negative correlations irrelevant.


#Run WGCNA
net = blockwiseModules(datExpr, corType = "pearson", maxBlockSize = 5000, 
                       networkType = "signed", power = power, minModuleSize =minModuleSize,
                       mergeCutHeight = 0.25, 
                       numericLabels = F, saveTOMs = TRUE, 
                       pamRespectsDendro = FALSE, saveTOMFileBase = "TOM")





```

## plot dendrogram of modules and heatmap of associated traits/ phenotypes
```{r}

#Hierarchical clustering of samples, detect outlier samples,and association of sample with certain trait
#with heatmap of such trait where red indicate high value

#Build adjacency matrix for samples
A = adjacency(data, type = "distance")
# this calculates the whole network connectivity
k = as.numeric(apply(A, 2, sum)) - 1
# standardized connectivity
Z.k = scale(k)
# Designate samples as outlying if their Z.k value is below the threshold
thresholdZ.k = -5  # often -2.5

# the color vector indicates outlyingness (red)
outlierColor = ifelse(Z.k < thresholdZ.k, "red", "black")

# calculate the cluster tree using flahsClust or hclust
sampleTree = flashClust(as.dist(1 - A), method = "average")
# Convert traits to a color representation: where red indicates high
# values
traitColors = data.frame(numbers2colors(as.numeric(metadata$cond_binary), signed = TRUE))
#dimnames(traitColors)[[2]] = "Inflammation_lvl"
datColors = data.frame(outlier_Samples = outlierColor, Condition= traitColors)
colnames(datColors)[2]= "Condition"
# Plot the sample dendrogram and the colors underneath.
png("plots/WGCNA_dendrogram.png", width = 8000, height = 6000, res= 600)
plotDendroAndColors(sampleTree, groupLabels = names(datColors), colors = datColors, cex.rowText = 5,
                    main = "Sample dendrogram and Homogeneity of samples heatmap")

#grid.arrange(a1, a2, nrow = 2)
dev.off()

```
## Plot the dendrogram and the module colors before and after merging underneath

```{r}

png("plots/dendrogram_merged_modules.png", width = 2200, height = 2500, res= 600)
plotDendroAndColors(net$dendrograms[[1]],  net$colors,
                    paste0("Modules"),
                    dendroLabels = FALSE,
                    addGuide = TRUE,
                    hang= 0.03,
                    cex.colorLabels = 0.6,
                    guideHang = 0.05)
dev.off()

#warning message:
#Error in .plotOrderedColorSubplot(order = order, colors = colors, rowLabels = rowLabels,  : 
 # Length of colors vector not compatible with number of objects in 'order'.
# for such error, make sure that you applied function goodsamplegene to exclude less variable genes or outlier samples before you run the model 
```
##  TOM plot/ heatmap of modules for all proteins

```{r}

dissTOM= 1 - TOMsimilarityFromExpr(datExpr, power= power) #datExpr samples in rows
dendro= net$dendrograms[[1]]
moduleColorsAutomatic= net$colors

#visualizations
png("plots/TOM_PLOT_module_heatmap.png", width = 800, height = 600)
#myheatcol = colorpanel(250,'gold',"orange",'darkred')
myheatcol = colorpanel(250,'red',"orange",'lemonchiffon')
# Transform dissTOM with a power to enhance visibility
TOMplot(dissTOM, dendro, moduleColorsAutomatic,col= myheatcol, 
        main = "Module Heatmap Plot, All Proteins")
dev.off()

```

## Module trait correlation heatmap plot
```{r, results = FALSE}

# Next use a single trait/variable or the whole metadata binarized to define the module significance 
#what module associated to what phenotype
#trait= metadata$diabetes

traits= design %>% as.data.frame()
head(traits)
# Define numbers of genes and samples
nSamples <- nrow(datExpr)
nGenes <- ncol(datExpr)
module_eigengenes= read.csv("output/module_eigengenes.csv") %>% column_to_rownames("X")
module.trait.corr <- WGCNA::cor(module_eigengenes, traits, use = 'p')
module.trait.corr.pvals <- corPvalueStudent(module.trait.corr, nSamples)

#module_trait heatmap of WGCNA package
# correlations and their p-values
png("plots/heatmap_module_trait_cor.png", width = 4000, height = 5500, res= 600) 
textMatrix = paste(signif(module.trait.corr, 2), "\n(", signif(module.trait.corr.pvals, 1), ")", 
                   sep = "")
dim(textMatrix) = dim(module.trait.corr)
par(mar = c(6, 6, 4, 6))
color= colorpanel(250,"#B0C4DE","#F7F5F4", "orange" )
#get shades of a color
# colfunc <-colorRampPalette(c("#F7F5F4" , "orange"),  alpha=T)
# color= colfunc(10)

#color= greenWhiteRed(50)
# Display the correlation values within a heatmap plot
labeledHeatmap(Matrix = module.trait.corr,  xLabels = colnames(traits),
               yLabels = names(module_eigengenes), 
               ySymbols = names(module_eigengenes), colorLabels = FALSE, colors = color, 
               textMatrix = textMatrix, setStdMargins = T, cex.text = 0.8,
               zlim = c(-1, 1),xColorWidth = 1 * strheight("M"),
               yColorWidth = 1.5 * strwidth("M"),xColorOffset = strheight("M")/6, 
               yColorOffset = strwidth("M")/6, font.lab.x = 2, cex.legendLabel = .4,
               font.lab.y = 2, xLabelsAngle = 45,
               main = paste("Module-Condition Relationship"), plotLegend= TRUE)

dev.off()
```

## chord plot of hubproteins
```{r}

hubs= read.csv("output/phenotype_cor_hubs.csv")

#build similarity/ design matrix
keydrivers= unlist(hubs) %>% unique(.) %>% .[. != ""]
mtx= matrix(nrow= ncol(hubs), ncol = length( keydrivers)) #number of all key drivers 
row.names(mtx)= gsub("_hub", "", names(hubs) )
colnames(mtx)= paste0(keydrivers)

#colnames of matrix included in keydrivers specified for certain module/ phenotype(rows) then put in 1
mod= apply(hubs, 2, function(x) as.list(x))

for (i in seq_along(mod)){
  for (j in 1:ncol(mtx)) {
    if ( colnames(mtx)[j] %in% mod[[i]] ) {
      mtx[i, j] <- 1
    } else {
      mtx[i, j] <- 0
    }
  }
}

library(circlize)
```

## visualize chordplot
```{r}
png("plots/chord_plot_hubproteins.png", width = 8000, height = 7000, res= 600)

#grid.col <- setNames(rainbow(length(unlist(dimnames(mtx)))), union(rownames(mtx), colnames(mtx)))
palt<- colorRampPalette(c("#F6E8C3", "#B0C4DE", "#E3B31C", "tan", "purple", "#523375" , "maroon3" , "#21908CFF" , "darkgrey",  "deepskyblue4" )) 

grid.col = palt(length(unlist(dimnames(mtx))))
grid.col= setNames(grid.col, union(rownames(mtx), colnames(mtx)))
grid.col[row.names(mtx)] = brewer.pal(n = dim(mtx)[1], name = "Dark2")

par(cex = .8, mar = c(0, 0, 0, 0))

circos.par(gap.degree = 1, 
           track.margin = c(0.05, 0.05), 
           points.overflow.warning = FALSE
) 

chordDiagram(mtx, 
             annotationTrack = "grid",
             transparency = 0.5,
             grid.col = grid.col)

# List of labels to add an asterisk to some important genes "CETP"  "ZMYM6" "SBSN" 
labels_to_asterisk <- c("CETP", "ZMYM6", "SBSN")
# Labels to be colored red
labels_red <- c("SBSN")

# Customize the labels to be perpendicular, add asterisks, and color specific labels red
circos.track(track.index = 1, panel.fun = function(x, y) {
  label <- CELL_META$sector.index
  # Append asterisk to all specified labels
  modified_label <-ifelse(label %in% labels_to_asterisk , paste0(label, " ***"), label )
  # Check if the label should also be colored red
  label_color <- ifelse(label %in% labels_red, "red", "black")
  
  circos.text(CELL_META$xcenter, CELL_META$cell.ylim[2]*3.5, # Adjust position as needed
              modified_label, col = label_color, facing = "clockwise", #facing = "outside", # for horizontal labels
              niceFacing = TRUE, adj = c(0, 0.5)) 
}, bg.border = NA)

circos.clear()
dev.off()

```

```{r}
#Intramodular analysis: identifying genes with high GS and MM
png("mm_vs_sig.png", width = 800, height = 600) 
colorOfColumn = substring(names(datKME), 4)
par(mar = c(5, 4, 4, 2) + 0.1) 
par(mfrow = c(2, 2))
selectModules = c( "brown","blue", "turquoise", "grey")
par(mfrow = c(2, length(selectModules)/2))
for (module in selectModules) {
  column = match(module, colorOfColumn)
  restModule = moduleColorsAutomatic == module
  verboseScatterplot(datKME[restModule, column], GS.lvl[restModule],
                     xlab = paste("Module Membership ",
                                  module, "module"), ylab = "pertubation_lvl", main = paste("kME.", module,
                                                                                            "vs. Protein Sig."), col = module)
  
}             
dev.off() 
```


```{r}

```


